---
linters:
  enable:
    - golint
    - goimports
    - gosec
    - misspell
    - unconvert
    - gocyclo
    - gocognit
    - godox
    - funlen
    - gomnd
run:
  tests: false
service:
  golangci-lint-version: 1.24.x
