---
linters:
  enable:
    - golint
    - goimports
    - gosec
    - misspell
    - unconvert
    - gocyclo
    - gocognit
    - godox
    - funlen
    - gomnd
run:
  tests: false
  timeout: 3m0s
  out-format: colored-line-number
  skip-dirs: gopath
  modules-download-mode: readonly
service:
  golangci-lint-version: 1.27.x
