---
linters:
  enable:
    - golint
    - goimports
    - gosec
    - misspell
    - unconvert
    - gocyclo
    - gocognit
    - godox
    - funlen
    - gomnd
run:
  tests: false
  timeout: 3m
  out-format: colored-line-number
  skip-dirs:
    - /home/travis/gopath/pkg/mod
  modules-download-mode: readonly
service:
  golangci-lint-version: 1.31.x
