---
linters:
  enable:
    - revive
    - goimports
    - gosec
    - misspell
    - unconvert
    - gocyclo
    - gocognit
    - godox
    - funlen
    - gomnd
    # enable for future
    # - bodyclose
    # - depguard
    # - durationcheck
    # - gocritic
    # - gofmt
    # - goheader
    # - nakedret
    # 
run:
  relative-path-mode: gomod
  tests: false
  timeout: 3m
  out-format: colored-line-number
  modules-download-mode: readonly
  allow-parallel-runners: true
service:
  golangci-lint-version: 1.49.0
