language: go
dist: xenial
os:
  - linux
env:
  global:
    # Force-enable Go modules. This will be unnecessary when Go 1.12 lands.
    - GO111MODULE=on
    - GOARCH=amd64
    # - CODECOV_TOKEN="9d27ab9c-c774-4583-8a46-f0b4380d374b"
stages:
  - checks
  - test
  - build
go:
  - 1.11.x
cache:
  directories: $GOPATH

# Only clone the most recent commit.
git:
  depth: 1

# Skip the install step. Don't `go get` dependencies. Only build with the code
# in vendor/
install: true

# script always runs to completion (set +e). If we have linter issues AND a
# failing test, we want to see both. Configure golangci-lint with a
# .golangci.yml file at the top level of your repo.
jobs:
  include:
    - stage: checks
      # script: golangci-lint run # run a bunch of code checkers/linters in parallel
      script:
        - curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin v1.16.0
        - golangci-lint --version # test that we got it
        - make download
        - golangci-lint run --issues-exit-code 0 --new-from-rev=HEAD~
    - stage: test
      script:
        - make coverage && bash <(curl -s https://codecov.io/bash)
    - stage: build
      script: make
      env: GOOS=linux
    - stage: build
      script: make
      env: GOOS=windows
    - stage: build
      script: make
      env: GOOS=darwin

deploy:
  on:
    tags: true
    condition: $TRAVIS_BUILD_STAGE_NAME = Build
  provider: releases
  api_key:
    secure: UZAAijNltt/1y9paip4U0quLiEEafq6Y5HSKYGMcpgYTuyp5sbyK7+kiiTAADahhN0UpyP9F4zfgcnEuISy1Ssr42zOHBVNeVQdGh1AJLTmi1Ne21vmbIVsRS6ZedmwvqiTw0GdmfXtcMx38S9QmJQtZrLuIY42irsPKbYmE/44SMzwoREed+jns1WkxxYqv92bLgAPrY2WiJpm0ZH90zcghflh7Mnr7s4hVPFB1R+OECE1pLeGYeuqMyto6eIPVkWSlrIfVjBXiMFHpsW3z2xYBFtu+ChBBftPw8RCeX8ustVtpD7Xe/XdpulZJ2EVR0VVRpoHcS1PJSWG8tORVXa/tQRU/k3Ymiv7VCKXnu7w0ELAO07VZsSLjcgUQ9mt9TIwSoCdj6pVSQpwT4POaaFR+gACf7ETVXqaDDIttjuA5SwWEHb4N0Y2O3FI1E/scoaS0WOJ1nZgMay26T9MuZhwufLUH5D7sEPiNKv90coZCK1+a7L8VEVm3+Xwvbpbrj6j/cF1aOoDYUuJPdP7511P+rAZFJSbE6S4BoM/3+M3dz5e18WTKAf8f6Kc/4F/eF2igOM5k7X/Gd3bpLwmUBZB8ZcAi4b62z1zIkQQn1On9gthIQ9C+ETJauhqP3aR23HzaYB5RG/AssN+XoInIVIET9L8GHpXWpFR11LZswrE=
  file_glob: true
  file: bridgr-*
  skip_cleanup: true
