---
# creates a YUM repository populated from Base or alternate sources
yum:
  repos:
    - https://dl.fedoraproject.org/pub/epel/7/x86_64/
  packages:
    - net-tools
    - postgis-2.0.7
    - htop
    # any form of package protocol/URI that is valid for YUM can be used in the "packages" section
    - https://rpmfind.net/linux/rpmfusion/free/el/updates/7/x86_64/f/ffmpeg-3.4.6-1.el7.x86_64.rpm

# creates a static rubygems repository
ruby:
  version: 2.4.5
  gems:
    - thor
    - package: rails
      version: ~5.1.0

# creates a PyPi compatible static repository, both packages and wheels
python:
  version: 2.7.5
  packages:
    - django
    - package: flask
      version: <3.4.1

# creates a static NPM repository site
npm:
  node_version: 10.0
  npm_version: 5.5
  packages:
    - express
    - package: vue-cli
      version: 3.0.1

# downloads docker images from provided image specs, and exports to file (or optionally, pushes to an alternate repository)
docker:
  repository: repository.internal.corp.com # exports to file if no target repo is specified
  images:
    - centos:7
    - image: ubuntu
      version: "18.04"
    - host: myrepo.org
      image: something/something/alpine
      version: latest
    - myrepo.org/alpine:3.7

# creates a Jenkins update site
jenkins:
  - pipeline
  - package: blueocean
    version: 2.2.1

# creates a static maven repository with POMs
maven:
  - apache-commons
  - junit:4
  - groupId: commons-io
    artifactId: commons-io
    version: 2.6
    packaging: jar # default if not specified

# creates bare git repositories to be statically hosted
git:
  - https://github.com/org/project.git # will create git/project.git bare repository

# downloads any files from a network source (HTTP/S only) and gathers them for static hosting
files:
  - https://server.com/releases/myfile.zip # will create files/myfile.zip
  - source: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 # will create files/assets/jq-linux64
    target: assets/

# downloads from vagrant cloud or local .box image, creating a vagrant box repository
vagrant:
  - centos/7
  - myimage.box
