---
# creates a YUM repository populated from Base or alternate sources
yum:
  repos:
    - https://dl.fedoraproject.org/pub/epel/7/x86_64/
  packages:
    - net-tools
    - postgis-2.0.7
    - htop
    # any form of package protocol/URI that is valid for YUM can be used in the "packages" section
    - https://rpmfind.net/linux/rpmfusion/free/el/updates/7/x86_64/f/ffmpeg-3.4.6-1.el7.x86_64.rpm

# creates a static rubygems repository
ruby:
  version: 2.4.5
  # sources can be populated if you need additional/alternative Rubygem repos. The default is rubygems.org
  # sources:
  #   - https://rubygems.org
  gems:
    - thor
    - package: rails
      version: ~>5.1.0

# creates a PyPi compatible static repository, both packages and wheels
python:
  # simplest case is a plain string array
  #- awscli
  # The version of python to use may be specified
  #version: 2.7.16
  packages:
    - django
    - package: flask
      version: <1.1.0

# creates a static NPM repository site
npm:
  node_version: 10.0
  npm_version: 5.5
  packages:
    - express
    - package: vue-cli
      version: 3.0.1

# downloads docker images from provided image specs, and exports to file (or optionally, pushes to an alternate repository)
docker:
  # a simple array can be used...
  #- docker.io/openshift/oauth-proxy:v1.1.0
  #- docker.io/openshift/origin-console:v3.11

  # Specifying repository key pushes images to the specified repository. If repository is _not_ specifed,
  # images are written to local filesystem as .tar files.
  #repository: repository.internal.corp.com
  images:
    - centos:7
    - image: ubuntu
      version: "18.04"
    - host: quay.io
      image: prometheus/node-exporter
      version: latest
    - quay.io/prometheus/prometheus:v2.11.2

# creates a Jenkins update site
jenkins:
  - pipeline
  - package: blueocean
    version: 2.2.1

# creates a static maven repository with POMs
maven:
  - apache-commons
  - junit:4
  - groupId: commons-io
    artifactId: commons-io
    version: 2.6
    packaging: jar # default if not specified

# creates bare git repositories to be statically hosted
git:
  - https://github.com/aztechian/bridgr.git # will create git/project.git bare repository
  - repo: https://github.com/kubernetes-sigs/kubespray
    bare: false
    # default branch is HEAD (ie, master) if not provided
    # branch: master
    tag: v2.11.0 # only one of "tag" or "branch" is allowed

# downloads any files from a network source (HTTP/S only) and gathers them for static hosting
files:
  - https://releases.hashicorp.com/packer/1.4.3/packer_1.4.3_linux_amd64.zip # will create files/packer_1.4.3_linux_amd64.zip
  - source: https://github.com/stedolan/jq/releases/download/jq-1.6/jq-linux64 # will create files/assets/jq-linux64
    target: assets/

# downloads from vagrant cloud or local .box image, creating a vagrant box repository
vagrant:
  - centos/7
  - myimage.box
