---
# git:
#   - https://github.com/redcanaryco/atomic-red-team.git
#   - repo: https://github.com/aztechian/infra.git
#     bare: false
# files:
#   - https://s3.imartin.io/minio/ian/5856b1184f6ae202fedf2789.png
#   - source: https://file.tar
#     target: ok.zip
# yum:
#   - package1
#   - vlc
python:
  version: "4.2"
  packages:
    - django
    - package: flask
      version: <1.1.0
