name: Compile Application

on:
  workflow_call:
    inputs:
      store_artifacts:
        default: false
        required: false
        type: boolean

jobs:
  compile:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [darwin, linux, windows]
        arch: [arm64, amd64, "386", arm]
        exclude:
          - os: windows
            arch: arm64
          - os: darwin
            arch: "386"
          - os: darwin
            arch: arm
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Compile Application
        env:
          GOOS: ${{ matrix.os }}
          GOARCH: ${{ matrix.arch }}
        run: |
          make download
          make
      - name: Store Build
        if: ${{ inputs.store_artifacts }}
        uses: actions/upload-artifact@v4.6.2
        with:
          name: bridgr-${{ matrix.os }}-${{ matrix.arch }}
          path: bridgr-*
          retention-days: 1
