name: CI Build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
defaults:
  run:
    shell: bash
jobs:
  setup:
    name: Setup Go and Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Setup bridger
        id: setup
        run: |
          echo "gcli_ver=$(grep golangci-lint .tool-versions | awk '{print $2}')" >> $GITHUB_OUTPUT
          echo "::group::godownload"
          make download
          echo "::endgroup::"
      - name: Run Linter and Review
        uses: reviewdog/action-golangci-lint@v2.8.0
        with:
          go_version_file: "go.mod"
          reporter: github-pr-review
          golangci_lint_version: "v${{ steps.setup.outputs.gcli_ver }}"
          cache: false
  test:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Setup Go
        uses: actions/setup-go@v5.5.0
        with:
          go-version-file: "go.mod"
          cache: true
      - name: Unit Test and Coverage
        uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: 7c1eabd638b12563c95fc1e17e4abc2440612eddd97b25273c986b24faddb6ae
        with:
          coverageCommand: make coverage
          prefix: github.com/aztechian/bridgr
          coverageLocations: |
            ${{github.workspace}}/coverage.out:gocov
  build:
    uses: ./.github/workflows/build.yaml
    needs: [setup]
