name: Deploy and Release
on:
  push:
    tags:
      - "v[0-9].[0-9].[0-9]*"
jobs:
  release-build:
    uses: ./.github/workflows/build.yaml
    with:
      store_artifacts: true

  reportcard:
    runs-on: ubuntu-latest
    needs: release-build
    steps:
      - name: Trigger goreportcard scan
        if: ${{ !env.ACT }}
        run: |
          curl -s -X POST -F "repo=github.com/$GITHUB_REPOSITORY" https://goreportcard.com/checks

  release:
    runs-on: ubuntu-latest
    needs: release-build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Download Build Files
        uses: actions/download-artifact@v3
      - name: Move files to root directory
        run: |
          mkdir -p release
          find ./bridgr-* -type f | xargs -I {} cp -v {} release/
      - name: Git Semantic Version
        uses: PaulHatch/semantic-version@v5.0.3
        with:
          major_pattern: "[MAJOR]"
          minor_pattern: "[MINOR]"
          version_format: "${major}.${minor}.${patch}-rc${increment}"
      - name: Release Changelog Builder
        id: changelog
        uses: mikepenz/release-changelog-builder-action@v3.6.0
        with:
          ignorePreReleases: true
          includeOpen: true
      - name: print
        run: echo "${{ steps.changelog.outputs.changelog }}"
      - name: Create Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: release/*
          prerelease: ${{ contains(github.ref, '-rc') }}
          body: ${{ steps.changelog.outputs.changelog }}
